### ISSUE TITLE
NoAuth error while defining first ACL on cluster using TLS & transport-layer client authentication

### ISSUE THREAD

**Issue by rcbjBlueMars** [bitnami/bitnami-docker-kafka#110]
**Description**

I have a set of ACL commnds that we are running to secure our kafka cluster. This script has worked well without issues on a local development environment for a cocuple of months. We are in the process of building out the system on AWS now. We've spun up the kafka and zookeeper clusters without issue. We are using TLS and client authentication to authenticate clients.

We tried to run our ACL script and it failed on the first create-acl.sh command with an exception about NoAuth. There is nothing printed to the zookeeper or kafka logs (including the authorizer log) that we enabled debug logging for.

We tried running a couple of different create-acl.sh commands that we are using. All of them get the same error very quickly.

**Steps to reproduce the issue:**

1. On the first node of a running kafka cluster using the bitnami kafka container and zookeeper container images, we try to define an ACL by running:
```
docker exec kafka0.example.org /opt/bitnami/kafka/bin/kafka-acls.sh --authorizer kafka.security.auth.SimpleAclAuthorizer --authorizer-properties zookeeper.connect=zookeeper0.myexample.org:2181  --add --cluster --allow-principal User:CN=kafka0.example.org,OU=Projects,O=NodeTest,L=XXXXXX,ST=XX,C=US --operation ClusterAction --force 
```
**Describe the results you received:**
The following error is generated quickly:
```
Error while executing ACL command: KeeperErrorCode = NoAuth for /kafka-acl
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /kafka-acl
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:116)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:560)
	at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1610)
	at kafka.zk.KafkaZkClient$$anonfun$createAclPaths$1.apply(KafkaZkClient.scala:1076)
	at kafka.zk.KafkaZkClient$$anonfun$createAclPaths$1.apply(KafkaZkClient.scala:1075)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at kafka.zk.KafkaZkClient.createAclPaths(KafkaZkClient.scala:1075)
	at kafka.security.auth.SimpleAclAuthorizer.configure(SimpleAclAuthorizer.scala:102)
	at kafka.admin.AclCommand$AuthorizerService.withAuthorizer(AclCommand.scala:205)
	at kafka.admin.AclCommand$AuthorizerService.addAcls(AclCommand.scala:213)
	at kafka.admin.AclCommand$.main(AclCommand.scala:62)
	at kafka.admin.AclCommand.main(AclCommand.scala)

```

**Describe the results you expected:**

I'm expecting it to successfully create the ACL on the cluster like it does on the local setup. 

**Additional information you deem important (e.g. issue happens only occasionally):**

We have a three node kafka cluster and a 3 node zookeeper cluster. We are testing with this setup locally and on AWS. 

**Version**
Kafka 2.3.0-0
Zookeeper 3.5.6-0

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1017-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.676GiB
 Name: ip-10-1-100-220
 ID: XKNJ:33XF:5ABH:7XJI:ZAFR:PVY7:BXRI:A63Q:FSPU:HCWP:MLYA:XELH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
OS:
Linux ip-10-1-100-220 5.3.0-1017-aws #18~18.04.1-Ubuntu SMP Wed Apr 8 15:12:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rafariossaa** [comment]
Hi @rcbjBlueMars,
  I was not able to reproduce the issue. This is what I did:
- Clone bitnami-docker-kafka repository:
```
$ git clone https://github.com/bitnami/bitnami-docker-kafka
```
- Rename the compose files to use the cluster one.
```
$ cd bitnami-docker-kafka
$ mv docker-compose.yml docker-compose.yml_single
$ cp docker-compose-cluster.yml docker-compose.yml
```
- Start the cluster
```
$ docker-compose up 
```
- Run the provided command
```
$ docker exec bitnami-docker-kafka_kafka_1 /opt/bitnami/kafka/bin/kafka-acls.sh --authorizer kafka.security.auth.SimpleAclAuthorizer --authorizer-properties zookeeper.connect=zookeeper:2181  --add --cluster --allow-principal
 User:CN=kafka0.example.org,OU=Projects,O=NodeTest,L=XXXXXX,ST=XX,C=US --operation ClusterAction --force 
Adding ACLs for resource `ResourcePattern(resourceType=CLUSTER, name=kafka-cluster, patternType=LITERAL)`: 
        (principal=User:CN=kafka0.example.org,OU=Projects,O=NodeTest,L=XXXXXX,ST=XX,C=US, host=*, operation=CLUSTER_ACTION, permissionType=ALLOW) 

Current ACLs for resource `ResourcePattern(resourceType=CLUSTER, name=kafka-cluster, patternType=LITERAL)`: 
        (principal=User:CN=kafka0.example.org,OU=Projects,O=NodeTest,L=XXXXXX,ST=XX,C=US, host=*, operation=CLUSTER_ACTION, permissionType=ALLOW) 
```
 Could you provide a docker-compose of your deployment ? Maybe is something related to the parameters you are using.
