### ISSUE TITLE
SASL_PLAINTEXT protocol not working

### ISSUE THREAD

**Issue by faustt93** [bitnami/bitnami-docker-kafka#117]
**Description**

When using `SASL_PLAINTEXT` in `KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP`, the kafka container cannot startup and report `/opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)`

Log:
```
[2020-07-17 09:50:47,992] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context [java.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf, zookeeper.sasl.client=default:true, zookeeper.sasl.clientconfig=default:Client]
        at org.apache.kafka.common.security.JaasUtils.isZkSaslEnabled(JaasUtils.java:67)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:388)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:210)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
        at kafka.Kafka$.main(Kafka.scala:82)
        at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
        at java.base/sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:255)
        at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:246)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245)
        at org.apache.kafka.common.security.JaasUtils.isZkSaslEnabled(JaasUtils.java:63)
        ... 5 more
Caused by: java.io.IOException: /opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)
        at java.base/sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:665)
        at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
        ... 16 more
```

**Steps to reproduce the issue:**

1. docker-compose.yml

```yaml
version: '2.0'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=tmpaaaa
  kafka:
    image: 'bitnami/kafka:2'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093,
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CLIENT_USER=powerlaw
      - KAFKA_CLIENT_PASSWORD=SVPcd54xsPYW6XEG
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=tmpaaaa
    depends_on:
      - zookeeper
```

**Describe the results you received:**

`/opt/bitnami/kafka/config/kafka_jaas.conf (No such file or directory)`

**Describe the results you expected:**

startup successfully

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 59
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: QRNO:AUQS:YWFO:XEWU:LLK4:EDEN:ZKCT:ZNTI:BRUC:O3XA:67KA:34C7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 44
  Goroutines: 58
  System Time: 2020-07-17T09:57:32.9261707Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://ubnhfz0l.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by faustt93** [comment]
And change the version of Kafka image to `2.4.1` will resolve this bug. Seems there is a bug in the 2.5.0 image.

**Comment by juan131** [comment]
Hi @faustt93 

Did you read the "Notable changes" section? We introduced several changes in Kafka 2.5 and, therefore, you need to adapt your Docker Compose to the new format of some env. variables. Please take a look to the link below:

- https://github.com/bitnami/bitnami-docker-kafka#250-debian-10-r51

**Comment by faustt93** [comment]
I can't figure out which change you mean.

> The environment variables KAFKA_PORT_NUMBER and KAFKA_CFG_PORT was deprecated, you can specify the port number in KAFKA_CFG_LISTENERS instead.
I don't think this change is related.

> The following environment variables were renamed:
> KAFKA_BROKER_USER -> KAFKA_CLIENT_USER
> KAFKA_BROKER_PASSWORD -> KAFKA_CLIENT_PASSWORD
Tried both. Use `KAFKA_CLIENT_USER` in my 2.5.0 config.

> Listeners & advertised listeners must be configured to enable authentication. Check Security section for more information.
Added `ALLOW_PLAINTEXT_LISTENER=yes`

**Comment by juan131** [comment]
Hi @faustt93 

Could you try using the Docker Compose below?? I basically added the `KAFKA_ZOOKEEPER_PROTOCOL` environment variable, and I used the listeners `INTERNAL/CLIENT` instead of `CLIENT/EXTERNAL`:

```yaml
version: '2.0'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=tmpaaaa
  kafka:
    image: 'bitnami/kafka:2'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://localhost:9093
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CLIENT_USER=powerlaw
      - KAFKA_CLIENT_PASSWORD=SVPcd54xsPYW6XEG
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=tmpaaaa
    depends_on:
      - zookeeper
```

**Comment by faustt93** [comment]
@juan131 I'll try this, thank you!
