### ISSUE TITLE
Zookeeper failing to run when using SASL_PLAINTEXT auth enable

### ISSUE THREAD

**Issue by arunkumart1992** [bitnami/bitnami-docker-kafka#137]
**Description**
**I got below error when deploying kafka and zookeeper. Please correct me if I'm using the wrong conf.**

```2021-01-07 12:43:45,864 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1420] - Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, session id = 0x10001dc16990006, negotiated timeout = 30000
WATCHER::
WatchedEvent state:SyncConnected type:None path:null
2021-01-07 12:43:45,907 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1272] - Session 0x10001dc16990006 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.lang.IllegalArgumentException
        at java.base/javax.security.auth.callback.NameCallback.<init>(NameCallback.java:87)
        at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.processChallenge(DigestMD5Client.java:326)
        at java.security.sasl/com.sun.security.sasl.digest.DigestMD5Client.evaluateChallenge(DigestMD5Client.java:220)
        at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:320)
        at org.apache.zookeeper.client.ZooKeeperSaslClient$1.run(ZooKeeperSaslClient.java:317)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
        at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslToken(ZooKeeperSaslClient.java:317)
        at org.apache.zookeeper.client.ZooKeeperSaslClient.respondToServer(ZooKeeperSaslClient.java:270)
        at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:918)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:96)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)
WATCHER::
WatchedEvent state:Disconnected type:None path:null
KeeperErrorCode = ConnectionLoss for /
2021-01-07 12:43:46,026 [myid:] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1
/opt/bitnami/java/bin/java
Connecting to localhost:2181
2021-01-07 12:43:51,727 [myid:] - INFO  [main:Environment@98] - Client environment:zookeeper.version=3.6.1--104dcb3e3fb464b30c5186d229e00af9f332524b, built on 04/21/2020 15:01 GMT
2021-01-07 12:43:51,744 [myid:] - INFO  [main:Environment@98] - Client environment:host.name=de767cc02e14
2021-01-07 12:43:51,744 [myid:] - INFO  [main:Environment@98] - Client environment:java.version=11.0.8
2021-01-07 12:43:51,746 [myid:] - INFO  [main:Environment@98] - Client environment:java.vendor=BellSoft
2021-01-07 12:43:51,746 [myid:] - INFO  [main:Environment@98] - Client environment:java.home=/opt/bitnami/java```

<!-- Briefly describe the problem you are having in a few paragraphs. -->

```[root@kafka0 kafka1]# cat docker-compose.yml
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.1'
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=test
  kafka:
    image: 'bitnami/kafka:2.6.0-debian-10-r4'
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://192.168.56.107:9093
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CLIENT_USER=test
      - KAFKA_CLIENT_PASSWORD=test
      - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.56.107:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=test
    depends_on:
      - zookeeper```




```

- Output of `docker info`:

```
[root@kafka0 kafka1]# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 20
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-1062.12.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 1
Total Memory: 4.442 GiB
Name: kafka0
ID: HV6R:CAD6:RCPM:Q5H4:XN3X:V37L:VBNZ:L3TI:HHWT:L45O:MGQP:VKCO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

-  `docker-compose version` (if applicable):

```
[root@kafka0 kafka1]# docker-compose --version
docker-compose version 1.23.2, build 1110ad01
[root@kafka0 kafka1]#

```

**Comment by miguelaeh** [comment]
Hi @arunkumart1992 ,
You are missing the `ZOO_CLENT_USER` and `ZOO_CLIENT_PASSWORD` env vars in Zookeper. Check this:
```
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.1'
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=test
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=test
  kafka:
    image: 'bitnami/kafka:2.6.0-debian-10-r4'
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093,
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,CLIENT://kafka:9093
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CLIENT_USER=test
      - KAFKA_CLIENT_PASSWORD=test
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=test
    depends_on:
      - zookeeper
 ```

**Comment by arunkumart1992** [comment]
Hi @miguelaeh 

Thanks for sharing the details. Could you please help, how to check if authentication works. I haven't tried SASL auth before

**Comment by arunkumart1992** [comment]
@miguelaeh Could you please help, how to check if authentication works. I haven't tried SASL auth before

**Comment by alemorcuq** [comment]
You can jump into the `kafka` container and run this:

```
$ /opt/bitnami/kafka/bin/zookeeper-shell.sh zookeeper:2181 get /
Connecting to zookeeper:2181

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /
```

And you see an error.

Then, passing the credentials:

```
$ KAFKA_OPTS="-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf" /opt/bitnami/kafka/bin/zookeeper-shell.sh zookeeper:2181 get /
Connecting to zookeeper:2181

WATCHER::

WatchedEvent state:SyncConnected type:None path:null

WATCHER::

WatchedEvent state:SaslAuthenticated type:None path:null
```

You see `SaslAuthenticated`.

**Comment by arunkumart1992** [comment]
@alemorcuq  Thanks for the update

I got below output when I tried below command

```I have no name!@conatiner:/$ /opt/bitnami/kafka/bin/zookeeper-shell.sh zookeeper:2181 get /
Connecting to zookeeper:2181

WATCHER::

WatchedEvent state:SyncConnected type:None path:null

I have no name!@35da6efb9277:/$```

Is the above out expected? Is this autheticated?

**Comment by hanwei-dev** [comment]
我也遇到同样的问题，请问如何解决的呀
