### ISSUE TITLE
log4j:ERROR Could not read configuration file from URL [file:/opt/bitnami/kafka/bin/../config/tools-log4j.properties].

### ISSUE THREAD

**Issue by mbana** [bitnami/bitnami-docker-kafka#15]
Creates the topic fine - it just looks like it can't find the `/opt/bitnami/kafka/conf/tools-log4j.properties` file:

```sh
$ find / -name "tools-log4j.properties"
find: `/root': Permission denied
find: `/proc/tty/driver': Permission denied
find: `/var/cache/ldconfig': Permission denied
/opt/bitnami/kafka/conf/tools-log4j.properties
find: `/etc/ssl/private': Permission denied
```

I guess I could symlink the file to `/opt/bitnami/kafka/bin/config` but I think this needs to get fixed upstream.

**Error log:**

```sh
$ docker run \
    --network="some_network" \
    -it \
    --rm \
    --name "topic_create" \
    -e "KAFKA_ZOOKEEPER_CONNECT=${ZOOKEEPER_HOST}" \
    -e "ALLOW_PLAINTEXT_LISTENER=yes" \
    "bitnami/kafka:1.1.0" /bin/bash

Welcome to the Bitnami kafka container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues

I have no name!@e6c4124a921d:/$ ZOOKEEPER_HOST="zookeeper:2181"
I have no name!@e6c4124a921d:/$ TOPIC_NAME="kafka-test-topic"
I have no name!@e6c4124a921d:/$ kafka-topics.sh --create --zookeeper "${ZOOKEEPER_HOST}" --topic "${TOPIC_NAME}" --partitions 1 --replication-factor 1
log4j:ERROR Could not read configuration file from URL [file:/opt/bitnami/kafka/bin/../config/tools-log4j.properties].
java.io.FileNotFoundException: /opt/bitnami/kafka/bin/../config/tools-log4j.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:42)
	at kafka.utils.Log4jControllerRegistration$.<init>(Logging.scala:25)
	at kafka.utils.Log4jControllerRegistration$.<clinit>(Logging.scala)
	at kafka.utils.Logging$class.$init$(Logging.scala:47)
	at kafka.admin.TopicCommand$.<init>(TopicCommand.scala:40)
	at kafka.admin.TopicCommand$.<clinit>(TopicCommand.scala)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
log4j:ERROR Ignoring configuration file [file:/opt/bitnami/kafka/bin/../config/tools-log4j.properties].
log4j:WARN No appenders could be found for logger (kafka.utils.Log4jControllerRegistration$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Error while executing topic command : Topic 'kafka-test-topic' already exists.
I have no name!@e6c4124a921d:/$ 
```

**Comment by marcosbc** [comment]
Hi! Thanks for reporting this issue, we have been able to reproduce it.

Our container initialization seems not to happen when running certain commands, and the configuration files are in the wrong place at that point, causing that error.

We'll work on fixing it and update this case with any progress.

**Comment by tompizmor** [comment]
Hello @mbana,

I just wanted to let you know that we have released a new revision of the Kafka image that fixes this issue. 
Could you try pulling the latest image and checking again? Please close the issue if you confirm that it works for you! Thanks!

**Comment by lupee431** [comment]
Hi 

Experiencing the same problem with kafka_2.11-2.0.0. 
I've made no changes to the configs.
This is straight out of the box.

Ideas?

Lew

**Comment by carrodher** [comment]
Hi @lupee431,

According to [Debian Dockerfile](https://github.com/bitnami/bitnami-docker-kafka/blob/2270b319a7116f15c31931d3d131dce8f7065e44/2/debian-9/Dockerfile#L10) or [OracleLinux Dockerfile](https://github.com/bitnami/bitnami-docker-kafka/blob/2270b319a7116f15c31931d3d131dce8f7065e44/2/ol-7/Dockerfile#L10), at this moment, kafka version is `kafka-2.0.1-0`, what do you mean with?
> Experiencing the same problem with kafka_2.11-2.0.0.

This versioning (`kafka_2.11-2.0.0`) is not familiar to me, are you using the Bitnami image?
