### ISSUE TITLE
Bitnami Kafka Connect deployment exits after connect-log4j.properties not found

### ISSUE THREAD

**Issue by pgobin** [bitnami/bitnami-docker-kafka#150]
**Description**

Kafka Connect deployed as described in the [official documentation](https://artifacthub.io/packages/helm/bitnami/kafka#deploying-extra-resources) (using `extraDeploy`) exits with the following error:
```
log4j:ERROR Could not read configuration file from URL [file:/opt/bitnami/kafka/bin/../config/connect-log4j.properties].
java.io.FileNotFoundException: /opt/bitnami/kafka/bin/../config/connect-log4j.properties (No such file or directory)
```

**Steps to reproduce the issue:**

1. From the [official documentation](https://artifacthub.io/packages/helm/bitnami/kafka#deploying-extra-resources):

> There are cases where you may want to deploy extra objects, such as Kafka Connect. For covering this case, the chart allows adding the full specification of other objects using the extraDeploy parameter.
>
> You can create the Kafka Connect image using the Dockerfile below:
> ```
> FROM bitnami/kafka:latest
> ...
> CMD /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/mongo.properties
> ```

2. Update `extraDeploy` verbatim replacing the `KAFKA-CONNECT-IMAGE` with the built Docker image.
3. Apply to Kubernetes cluster.
3. Check pod logs.

**Describe the results you received:**

Full log:

```
[38;5;6m [38;5;5m23:52:26.98 [0m
[38;5;6m [38;5;5m23:52:26.99 [0m[1mWelcome to the Bitnami kafka container[0m
[38;5;6m [38;5;5m23:52:26.99 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-kafka[0m
[38;5;6m [38;5;5m23:52:26.99 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-kafka/issues[0m
[38;5;6m [38;5;5m23:52:27.00 [0m
log4j:ERROR Could not read configuration file from URL [file:/opt/bitnami/kafka/bin/../config/connect-log4j.properties].
java.io.FileNotFoundException: /opt/bitnami/kafka/bin/../config/connect-log4j.properties (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
    at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
    at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
    at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
    at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
    at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
    at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
    at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
    at org.apache.kafka.connect.cli.ConnectStandalone.<clinit>(ConnectStandalone.java:58)
log4j:ERROR Ignoring configuration file [file:/opt/bitnami/kafka/bin/../config/connect-log4j.properties].
log4j:WARN No appenders could be found for logger (org.apache.kafka.connect.cli.ConnectStandalone).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 123
  Running: 25
  Paused: 0
  Stopped: 98
 Images: 200
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 4.825GiB
 Name: docker-desktop
 ID: GC2L:UWLK:Z3VA:V7AE:Q67Q:NVSC:PG6B:ZGCS:T46U:KH2T:5KBE:JQCA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker Desktop Kubernetes

Please assist. Thanks!

**Comment by andresbono** [comment]
Hi @pgobin, the file exists in the Kafka image:

```console
$ docker run --rm -it --entrypoint ls bitnami/kafka:2.7.0-debian-10-r93 /opt/bitnami/kafka/bin/../config/connect-log4j.properties
/opt/bitnami/kafka/bin/../config/connect-log4j.properties
```

So I'd say that the problem is that the `ConfigMap` that is mounted in the _connect_ container is overwriting the directory. Maybe the mountPath can be changed to `/bitnami/kafka/config` and the following logic will be applied when starting the container:

https://github.com/bitnami/bitnami-docker-kafka/blob/04eceab6e4ceb5a9f20a58d4fa7468d4d2522dca/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L663-L666

Could you check if that is the case?

**Comment by pgobin** [comment]
Thanks, @andresbono. Updating `mountPath` with `/bitnami/kafka/config` as you suggested stopped the overwrite that led to the exception. I didn't see the mounted files copied to the default config directory in `/opt/bitnami/kafka/config`. Either way, this fixed it. Thanks again.

**Comment by andresbono** [comment]
That's great! Thanks for confirming it.
