### ISSUE TITLE
2.8.0 does not seem to honor KAFKA_MOUNTED_CONF_DIR

### ISSUE THREAD

**Issue by raffaelespazzoli** [bitnami/bitnami-docker-kafka#168]
**Description**

I have had a 2.7.0 setup working based on the `KAFKA_MOUNTED_CONF_DIR`  env variable. After inadvertently migrating to 2.8.0, my configuration stopped working and the image was clearly not reading the config at the `KAFKA_MOUNTED_CONF_DIR1` location.

In my configuration certs and other SSL-related properties are defined in the mounted property file.
When using 2.8.0 the container errors out complaining that it cannot find the needed certs.

**Additional information you deem important (e.g. issue happens only occasionally):**

It would be nice if this image supported passing all the images via config file. Instead I found out that the following must be passed via environment variables:
```
        - name: KAFKA_CFG_LISTENERS
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_ZOOKEEPER_PROTOCOL
```
this create potential for discrepancy between the config file and the environment variables.

I'm running this image in OpenShift 4.7.

**Comment by alemorcuq** [comment]
Hi, @raffaelespazzoli.

A recent PR (#164) fixed an issue that made the container look for the truststore in the wrong place. Can you check that the image you are using contains that change and that the certs are where the container expects them to be?

**Comment by raffaelespazzoli** [comment]
I don't know how to check if the image I'm using has the change. I know that the 2.8.0 still have the issue at the time of wirting this message.

**Comment by raffaelespazzoli** [comment]
I still confirm the following:
1. when configuring the `KAFKA_MOUNTED_CONF_DIR` the initial script still requires some other environment variables which will the be ignored. Since they are required one would expect they would be merged with the passed server.properties.
2. in 2.8.0 the initial script also requires certs to be present at this location: `/bitnami/kafka/config/certs` while in 2.7.0 they were supposed to be here `/config/certs`.

I'd ask to disable all the check if the `KAFKA_MOUNTED_CONF_DIR` env is passed and trust the use to have done a correct configuration. 

As of now, I can't find a way to use 2.8.0 with `KAFKA_MOUNTED_CONF_DIR`. In my case the kafka container is failing as follows:
```
[38;5;6mkafka [38;5;5m13:16:37.18 [0m
[38;5;6mkafka [38;5;5m13:16:37.18 [0m[1mWelcome to the Bitnami kafka container[0m
[38;5;6mkafka [38;5;5m13:16:37.18 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-kafka[0m
[38;5;6mkafka [38;5;5m13:16:37.18 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-kafka/issues[0m
[38;5;6mkafka [38;5;5m13:16:37.18 [0m
[38;5;6mkafka [38;5;5m13:16:37.18 [0m[38;5;2mINFO [0m ==> ** Starting Kafka setup **
[38;5;6mkafka [38;5;5m13:16:37.24 [0m[38;5;2mINFO [0m ==> Initializing Kafka...
[38;5;6mkafka [38;5;5m13:16:37.24 [0m[38;5;2mINFO [0m ==> No injected configuration files found, creating default config files
[38;5;6mkafka [38;5;5m13:16:37.31 [0m[38;5;2mINFO [0m ==> Configuring Kafka for client communications with SSL authentication.

[38;5;6mkafka [38;5;5m13:16:37.33 [0m[38;5;2mINFO [0m ==> ** Kafka setup finished! **
[38;5;6mkafka [38;5;5m13:16:37.35 [0m[38;5;2mINFO [0m ==> ** Starting Kafka **
[2021-06-26 13:16:39,234] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2021-06-26 13:16:40,847] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
[2021-06-26 13:16:40,931] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
java.lang.IllegalArgumentException: Error creating broker listeners from 'PLAINTEXT://:9092': No security protocol defined for listener PLAINTEXT
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:273)
	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1840)
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1929)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1896)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1389)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1327)
	at kafka.Kafka$.buildServer(Kafka.scala:67)
	at kafka.Kafka$.main(Kafka.scala:87)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener PLAINTEXT
	at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:48)
	at scala.collection.immutable.Map$Map3.getOrElse(Map.scala:335)
	at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:48)
	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:53)
	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:270)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:270)
	... 8 more
```

this error seems to indicate that the container is trying to use the env variables and did ignore my config file. Same config with 2.7.0 works.

**Comment by raffaelespazzoli** [comment]
I found that the only way to use my config file in 2.8.0 was to put it in the `/bitnami/kafka/config` directory.

**Comment by alemorcuq** [comment]
Which tag are you using, @raffaelespazzoli ?
