### ISSUE TITLE
run as root fail

### ISSUE THREAD

**Issue by dulm** [bitnami/bitnami-docker-kafka#221]
**Description**

**Steps to reproduce the issue:**

1. as https://docs.bitnami.com/tutorials/work-with-non-root-containers/#using-non-root-containers-as-root-containers descripted, add `user: root` after image:xxx  in docker-compose.yml
2. run docker-composit up -d

**Describe the results you received:**
start failed, 

` docker logs kafka-zookeeper-1 `

```
2022-01-26 07:00:37,511 [myid:1] - ERROR [main:ZooKeeperServerMain@81] - Unable to access datadir, exiting abnormally
org.apache.zookeeper.server.persistence.FileTxnSnapLog$DatadirException: Cannot write to data directory /bitnami/zookeeper/data/version-2
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:140)
        at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:139)
        at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:113)
        at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:68)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:141)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:91)
Unable to access datadir, exiting abnormally
2022-01-26 07:00:37,517 [myid:1] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2022-01-26 07:00:37,519 [myid:1] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 3
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

**Comment by juan131** [comment]
Hi @dulm 

The issue is in the ZooKeeper container, right? Could you please open a new issue describing the same problem at https://github.com/bitnami/bitnami-docker-zookeeper/issues? Thanks in advance
