### ISSUE TITLE
Kafka Security SASL_PLAINTEXT Failed to create SaslClient with mechanism PLAIN

### ISSUE THREAD

**Issue by Ch33s3Burger** [bitnami/bitnami-docker-kafka#229]
### Name and Version

bitnami/kafka:3.1.0

### What steps will reproduce the bug?

I setup Zookeeper and Kafka with docker-compose.
My docker-compose.yml file looks like this:
```yaml
version: '3'

services:
    zookeeper:
        container_name: zookeeper
        image: zookeeper:3.7.0
        ports:
          - "2181"
        environment:
          - SERVER_JVMFLAGS=-Djava.security.auth.login.config=/etc/zookeeper/conf/zookeeper_jaas.conf
          - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/zookeeper/conf/kafka_jaas.conf
        volumes:
          - ./zoo.cfg:/conf/zoo.cfg
          - ./zookeeper_jaas.conf:/etc/zookeeper/conf/zookeeper_jaas.conf
          - ./kafka_jaas.conf:/etc/zookeeper/conf/kafka_jaas.conf
    kafka:
        image: 'bitnami/kafka:3.1.0'
        container_name: "kafka"
        ports:
          - '9093:9093'
        environment:
          - BITNAMI_DEBUG=true
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf
        depends_on:
          - zookeeper
        volumes:
          - ./keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks
          - ./truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks
          - ./server.properties:/bitnami/kafka/config/server.properties
          - ./kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
```
My zoo.cfg looks like this:
```
# The number of milliseconds of each tick.
tickTime=2000

# The number of ticks that the initial synchronization phase can take.
initLimit=10

# The number of ticks that can pass between sending a request and getting an acknowledgement.
syncLimit=5

# The port at which the clients will connect.
clientPort=2181

# The port address at which the clients will connect.
#clientPortAddress=0.0.0.0

# The directory where the snapshot data is stored.
dataDir=/tmp/data

# The directory the transaction log of updates is stored.
dataLogDir=/tmp/data-log

# Security
authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
java.security.auth.login.config=/etc/zookeeper/conf/zookeeper_jaas.conf
```
My server.properties for Kafka looks like this:
```
# Server Basics
broker.id=11

# Socket Server Settings
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600

# Log Basics
log.dirs=/bitnami/kafka/data
num.partitions=1
num.recovery.threads.per.data.dir=1

# Log Retention Policy
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000

# Internal Topic Settings
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

# Zookeeper
zookeeper.connect=zookeeper:2181
zookeeper.connection.timeout.ms=1000000

# Enable SSL security protocol for inter-broker communication
# Enable SASL_SSL security protocol for broker-client communication
listeners=INTERNAL://:9092,CLIENT://:9093
advertised.listeners=INTERNAL://kafka:9092,CLIENT://kafka:9093
listener.security.protocol.map=INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_SSL

# Group Coordinator Settings
group.initial.rebalance.delay.ms=0
auto.create.topics.enable=true
inter.broker.listener.name=INTERNAL

max.partition.fetch.bytes=1048576
max.request.size=1048576
sasl.enabled.mechanisms=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.mechanism=SCRAM-SHA-512
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=true

ssl.endpoint.identification.algorithm=

# SSL settings
ssl.keystore.type=JKS
ssl.truststore.type=JKS
ssl.key.password=secure_password
ssl.keystore.location=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
ssl.keystore.password=secure_password
ssl.truststore.password=secure_password
```
My zookeeper_jaas.conf  for the Zookeeper JAAS config looks like this:
```
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="zookeeper"
    password="zookeeper_password"
    user_kafka="kafka_password";
};
```
My kafka_jaas.conf looks like this:
```
KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="user"
    password="bitnami";
};

KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    user_user="bitnami";
    org.apache.kafka.common.security.scram.ScramLoginModule required;
};

Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka"
    password="kafka_password";
};
```

### What is the expected behavior?

Kafka successfully connects to Zookeeper which can be seen in the Zookeeper logs:
```
2022-02-25 10:00:45,664 [myid:] - INFO  [NIOWorkerThread-5:SaslServerCallbackHandler@119] - Successfully authenticated client: authenticationID=kafka;  authorizationID=kafka.
2022-02-25 10:00:45,684 [myid:] - INFO  [NIOWorkerThread-5:SaslServerCallbackHandler@135] - Setting authorizedID: kafka
2022-02-25 10:00:45,684 [myid:] - INFO  [NIOWorkerThread-5:ZooKeeperServer@1727] - Session 0x1000550996f0000: adding SASL authorization for authorizationID: kafka
2022-02-25 10:00:46,746 [myid:] - INFO  [NIOWorkerThread-11:SaslServerCallbackHandler@119] - Successfully authenticated client: authenticationID=kafka;  authorizationID=kafka.
2022-02-25 10:00:46,746 [myid:] - INFO  [NIOWorkerThread-11:SaslServerCallbackHandler@135] - Setting authorizedID: kafka
2022-02-25 10:00:46,746 [myid:] - INFO  [NIOWorkerThread-11:ZooKeeperServer@1727] - Session 0x1000550996f0001: adding SASL authorization for authorizationID: kafka
```

### What do you see instead?

So the connection seems to work but Kafka throws many exceptions every second. They look like the following:
```
[2022-02-25 10:00:46,814] INFO [Controller id=11, targetBrokerId=11] Failed to create channel due to  (org.apache.kafka.common.network.SaslChannelBuilder)
org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism PLAIN
Caused by: javax.security.sasl.SaslException: Cannot get userid/password [Caused by javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.]
	at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:157)
	at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:94)
	at java.security.sasl/javax.security.sasl.Sasl.createSaslClient(Sasl.java:433)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslClient$0(SaslClientAuthenticator.java:219)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslClient(SaslClientAuthenticator.java:215)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.<init>(SaslClientAuthenticator.java:206)
	at org.apache.kafka.common.network.SaslChannelBuilder.buildClientAuthenticator(SaslChannelBuilder.java:286)
	at org.apache.kafka.common.network.SaslChannelBuilder.lambda$buildChannel$1(SaslChannelBuilder.java:228)
	at org.apache.kafka.common.network.KafkaChannel.<init>(KafkaChannel.java:143)
	at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:236)
	at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338)
	at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:256)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:986)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:64)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:291)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:245)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:73)
	at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:136)
	... 20 more
[2022-02-25 10:00:46,822] WARN [Controller id=11, targetBrokerId=11] Error connecting to node kafka:9092 (id: 11 rack: null) (org.apache.kafka.clients.NetworkClient)
java.io.IOException: Channel could not be created for socket java.nio.channels.SocketChannel[closed]
	at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:348)
	at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:256)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:986)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:64)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:291)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:245)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
	at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:240)
	at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338)
	... 8 more
```

### Additional information

I would like to know two things.
1. First how do I fix Kafka to not throw that error all the time?
2. And the other one is that I am using the environment variable "ALLOW_PLAINTEXT_LISTENER=yes". As the logs say I should not use this when running in production. But if I remove it Kafka does not even start. How can I fix this?

**Comment by javsalgar** [comment]
Hi,

Looking at the configuration, it is not clear to me if the issue has to do with the Bitnami packaging or the configuration you are using. Did you check with the Kakfa developers in their support forum?
