### ISSUE TITLE
Kafka not start with Invalid Receive Error

### ISSUE THREAD

**Issue by afzdev13** [bitnami/bitnami-docker-kafka#249]
### Name and Version

bitname/kafka:2.8.1

### What steps will reproduce the bug?

1. Setup docker-compose.yml like that:

```
version: '3.9'

networks:
  kafka-network:
    driver: overlay

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    deploy:
      placement:
        constraints:
          - node.role == manager
```

2- Run the command:
> sudo docker stack deploy -c docker-compose.yml w2

### What is the expected behavior?

I just need the kafka is being able to receive consumers and producers

### What do you see instead?

Im receiving this error in logs:

```
  | [2022-05-09 14:42:40,896] WARN [SocketServer listenerType=ZK_BROKER, nodeId=1] Unexpected error from /10.0.12.4; closing connection (org.apache.kafka.common.network.Selector)
  | org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295617 larger than 104857600)
  | 	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
  | 	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
  | 	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
  | 	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
  | 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
  | 	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
  | 	at kafka.network.Processor.poll(SocketServer.scala:989)
  | 	at kafka.network.Processor.run(SocketServer.scala:892)
  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Additional information

With these same settings it was working, the error started suddenly without modifying these settings, I read on the stackoverflow that it could be some other process running on the zookeeper or kafka port but there is nothing running there, the error started after I added a snippet in the code from application that uses kafkajs to create an administrator and create topics before all the rest of the application happens, removing the code the error still persists and I believe it has nothing to do with this error because even the first time it ran it didn't managed to connect to kafka because it did not start with this error.

Last Code added:

```js
  async create() {
    const kafka = new Kafka({
      clientId: "my-app",
      brokers: [process.env.BOOTSTRAP_SERVER],
      ssl: { rejectUnauthorized: false },
    });
    const admin = kafka.admin();
    await admin.connect();
    TopicsList.forEach(async topic => {
      await admin.createTopics({topics:[{topic, replicationFactor:3, numPartitions:6}]} );
    })
    await admin.disconnect();
  }
```

**Comment by afzdev13** [comment]
Removing the last code make works so the error is not in bitname kafka image

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for coming back and sharing your findings.
