### ISSUE TITLE
Kafka and zookeeper servers exits

### ISSUE THREAD

**Issue by djklim87** [bitnami/bitnami-docker-kafka#32]
Kafka and zookeeper servers exits after command docker run. How i can catch error?
Starts by your guide https://github.com/bitnami/bitnami-docker-kafka#using-the-command-line

Ofcourse whel i launch kafka client i getting error:

`
[2018-11-18 15:48:19,339] WARN Session 0x0 for server zookeeper-server:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
`

**Comment by djklim87** [comment]
I find solution. You forget add in commands - `ALLOW_PLAINTEXT_LISTENER=yes` and `ALLOW_ANONYMOUS_LOGIN=yes`
