### ISSUE TITLE
Error Connect to Zookeeper

### ISSUE THREAD

**Issue by MohMehrnia** [bitnami/bitnami-docker-kafka#37]
I try connet Kafka docker to zookeeper and show me below erorr:

```
Opening socket connection to server zookeeper:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
```

My Execure Command for create containers is 

```
docker run -p 5000:2181 -e ALLOW_ANONYMOUS_LOGIN=yes -v D:/Databases/zookeeper:/bitnami/zookeeper --network app-tier  -d --name zookeeper-server  bitnami/zookeeper:latest
```

```
docker run -p 9092:9092 -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:5000 -v D:/Databases/Kafka:/bitnami/kafka --network app-tier -d --name kafka-server bitnami/kafka:latest
```
How Can fixed?

**Comment by andresbono** [comment]
Hi @MohMehrnia,

you are setting `KAFKA_ZOOKEEPER_CONNECT=zookeeper:5000`. Does `zookeeper` resolve to the host where the Zookeeper container is running?

For instance, if you are running both containers in the same host, you should be setting the environment variable to `KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:5000`, the loopback address.

**Comment by MohMehrnia** [comment]
I run you instruction and show me this error

My Command is
`docker run -p 9092:9092 -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:5000 -v D:/Databases/Kafka:/bitnami/kafka --network app-tier -d --name kafka-server bitnami/kafka:latest`

Welcome to the Bitnami kafka container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues

WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing kafka
kafka   INFO  ==> Validating inputs...
kafka   INFO  ==> No injected configuration files found. Creating default config files...
kafka   INFO  ==> Deploying Kafka from scratch...
nami    INFO  kafka successfully initialized
INFO  ==> Starting kafka...
[2019-01-02 17:14:31,797] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2019-01-02 17:14:36,420] INFO starting (kafka.server.KafkaServer)
[2019-01-02 17:14:36,450] INFO Connecting to zookeeper on 127.0.0.1:5000 (kafka.server.KafkaServer)
[2019-01-02 17:14:36,683] INFO [ZooKeeperClient] Initializing a new session to 127.0.0.1:5000. (kafka.zookeeper.ZooKeeperClient)
[2019-01-02 17:14:36,706] INFO Client environment:zookeeper.version=3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03, built on 06/29/2018 00:39 GMT (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,706] INFO Client environment:host.name=a9afd5d88774 (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,706] INFO Client environment:java.version=1.8.0_191-ojdkbuild (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,706] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,706] INFO Client environment:java.home=/opt/bitnami/java (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,707] INFO Client environment:java.class.path=/opt/bitnami/kafka/bin/../libs/activation-1.1.1.jar:/opt/bitnami/kafka/bin/../libs/aopalliance-repackaged-2.5.0-b42.jar:/opt/bitnami/kafka/bin/../libs/argparse4j-0.7.0.jar:/opt/bitnami/kafka/bin/../libs/audience-annotations-0.5.0.jar:/opt/bitnami/kafka/bin/../libs/commons-lang3-3.5.jar:/opt/bitnami/kafka/bin/../libs/compileScala.mapping:/opt/bitnami/kafka/bin/../libs/compileScala.mapping.asc:/opt/bitnami/kafka/bin/../libs/connect-api-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/connect-basic-auth-extension-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/connect-file-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/connect-json-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/connect-runtime-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/connect-transforms-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/guava-20.0.jar:/opt/bitnami/kafka/bin/../libs/hk2-api-2.5.0-b42.jar:/opt/bitnami/kafka/bin/../libs/hk2-locator-2.5.0-b42.jar:/opt/bitnami/kafka/bin/../libs/hk2-utils-2.5.0-b42.jar:/opt/bitnami/kafka/bin/../libs/jackson-annotations-2.9.7.jar:/opt/bitnami/kafka/bin/../libs/jackson-core-2.9.7.jar:/opt/bitnami/kafka/bin/../libs/jackson-databind-2.9.7.jar:/opt/bitnami/kafka/bin/../libs/jackson-jaxrs-base-2.9.7.jar:/opt/bitnami/kafka/bin/../libs/jackson-jaxrs-json-provider-2.9.7.jar:/opt/bitnami/kafka/bin/../libs/jackson-module-jaxb-annotations-2.9.7.jar:/opt/bitnami/kafka/bin/../libs/javassist-3.22.0-CR2.jar:/opt/bitnami/kafka/bin/../libs/javax.annotation-api-1.2.jar:/opt/bitnami/kafka/bin/../libs/javax.inject-1.jar:/opt/bitnami/kafka/bin/../libs/javax.inject-2.5.0-b42.jar:/opt/bitnami/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/bitnami/kafka/bin/../libs/javax.ws.rs-api-2.1.1.jar:/opt/bitnami/kafka/bin/../libs/javax.ws.rs-api-2.1.jar:/opt/bitnami/kafka/bin/../libs/jaxb-api-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/jersey-client-2.27.jar:/opt/bitnami/kafka/bin/../libs/jersey-common-2.27.jar:/opt/bitnami/kafka/bin/../libs/jersey-container-servlet-2.27.jar:/opt/bitnami/kafka/bin/../libs/jersey-container-servlet-core-2.27.jar:/opt/bitnami/kafka/bin/../libs/jersey-hk2-2.27.jar:/opt/bitnami/kafka/bin/../libs/jersey-media-jaxb-2.27.jar:/opt/bitnami/kafka/bin/../libs/jersey-server-2.27.jar:/opt/bitnami/kafka/bin/../libs/jetty-client-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-continuation-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-http-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-io-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-security-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-server-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-servlet-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-servlets-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jetty-util-9.4.12.v20180830.jar:/opt/bitnami/kafka/bin/../libs/jopt-simple-5.0.4.jar:/opt/bitnami/kafka/bin/../libs/kafka-clients-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-log4j-appender-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-examples-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-scala_2.11-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-test-utils-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-tools-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/kafka_2.11-2.1.0-sources.jar:/opt/bitnami/kafka/bin/../libs/kafka_2.11-2.1.0.jar:/opt/bitnami/kafka/bin/../libs/log4j-1.2.17.jar:/opt/bitnami/kafka/bin/../libs/lz4-java-1.5.0.jar:/opt/bitnami/kafka/bin/../libs/maven-artifact-3.5.4.jar:/opt/bitnami/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/bitnami/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/bitnami/kafka/bin/../libs/plexus-utils-3.1.0.jar:/opt/bitnami/kafka/bin/../libs/reflections-0.9.11.jar:/opt/bitnami/kafka/bin/../libs/rocksdbjni-5.14.2.jar:/opt/bitnami/kafka/bin/../libs/scala-library-2.11.12.jar:/opt/bitnami/kafka/bin/../libs/scala-logging_2.11-3.9.0.jar:/opt/bitnami/kafka/bin/../libs/scala-reflect-2.11.12.jar:/opt/bitnami/kafka/bin/../libs/slf4j-api-1.7.25.jar:/opt/bitnami/kafka/bin/../libs/slf4j-log4j12-1.7.25.jar:/opt/bitnami/kafka/bin/../libs/snappy-java-1.1.7.2.jar:/opt/bitnami/kafka/bin/../libs/validation-api-1.1.0.Final.jar:/opt/bitnami/kafka/bin/../libs/zkclient-0.10.jar:/opt/bitnami/kafka/bin/../libs/zookeeper-3.4.13.jar:/opt/bitnami/kafka/bin/../libs/zstd-jni-1.3.5-4.jar (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,707] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:os.version=4.9.125-linuxkit (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:user.name=? (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:user.home=? (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,708] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,711] INFO Initiating client connection, connectString=127.0.0.1:5000 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@1623b78d (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:36,854] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-01-02 17:14:36,859] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:36,919] INFO Socket error occurred: localhost/127.0.0.1:5000: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:38,023] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:38,025] INFO Socket error occurred: localhost/127.0.0.1:5000: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:39,127] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:39,129] INFO Socket error occurred: localhost/127.0.0.1:5000: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:40,230] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:40,238] INFO Socket error occurred: localhost/127.0.0.1:5000: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:41,339] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:41,340] INFO Socket error occurred: localhost/127.0.0.1:5000: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:42,441] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:42,443] INFO Socket error occurred: localhost/127.0.0.1:5000: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:42,862] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
[2019-01-02 17:14:43,544] INFO Opening socket connection to server localhost/127.0.0.1:5000. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:43,686] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
[2019-01-02 17:14:43,687] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
[2019-01-02 17:14:43,692] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
[2019-01-02 17:14:43,714] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:268)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:264)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:264)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:264)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:97)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1693)
        at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:348)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)
[2019-01-02 17:14:43,738] INFO shutting down (kafka.server.KafkaServer)
[2019-01-02 17:14:43,770] INFO shut down completed (kafka.server.KafkaServer)
[2019-01-02 17:14:43,772] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2019-01-02 17:14:43,777] INFO shutting down (kafka.server.KafkaServer)

**Comment by andresbono** [comment]
Can you share the details of your docker network? You can execute the following command:

```
docker network inspect app-tier
```


Also try to use the container name and internal port to connect to zookeeper:

`KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181`

```
docker run -p 9092:9092 -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181 -v D:/Databases/Kafka:/bitnami/kafka --network app-tier -d --name kafka-server bitnami/kafka:latest
```

**Comment by MohMehrnia** [comment]
thanks for helping,
app-tier insect:
[
    {
        "Name": "app-tier",
        "Id": "a980212ae70310eaa92d815e3d680fa6902c5c9f2f7c79ef091d4af2be7c0df7",
        "Created": "2019-01-01T04:57:59.0390985Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

**Comment by MohMehrnia** [comment]
Yes, I try and not working

**Comment by MohMehrnia** [comment]
Hi, it's work when firewall disabled

**Comment by MohMehrnia** [comment]
I run below container and it's work

`https://github.com/hey-johnnypark/docker-kafka-zookeeper`

Why i can not start kafka with bitnami ?

**Comment by MohMehrnia** [comment]
Thanks, I execute your command and It's Work.

**Comment by andresbono** [comment]
Great @MohMehrnia!

Can we help you with anything else? Did you clean the old kafka volumes?

**Comment by MohMehrnia** [comment]
Yes, i clean old volume and create new volume and execute command and success, thanks for helping me

**Comment by andresbono** [comment]
Nice! Thanks for letting us know.
