### ISSUE TITLE
Exception while loading Zookeeper JAAS login context 'Client' JAAS file not found

### ISSUE THREAD

**Issue by Aravindumasankar** [bitnami/bitnami-docker-kafka#44]
```
bitnami    INFO  Initializing kafka
kafka   INFO  ==&gt; Validating inputs...
kafka   INFO  ==&gt; Configuration file found...
kafka   INFO  ==&gt; Deploying Kafka from scratch...
nami    INFO  kafka successfully initialized
INFO  ==&gt; Starting kafka... 
[2019-03-28 12:45:10,333] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2019-03-28 12:45:10,688] INFO starting (kafka.server.KafkaServer)
[2019-03-28 12:45:10,689] INFO Connecting to zookeeper on dev01-zookeeper-headless.core-services-dev01:2181 (kafka.server.KafkaServer)
[2019-03-28 12:45:10,698] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context 'Client'
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:45)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:358)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
	at sun.security.provider.ConfigFile$Spi.&lt;init&gt;(ConfigFile.java:137)
	at sun.security.provider.ConfigFile.&lt;init&gt;(ConfigFile.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:42)
	... 5 more
Caused by: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
	at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:666)
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
	at sun.security.provider.ConfigFile$Spi.&lt;init&gt;(ConfigFile.java:135)
	... 16 more
[2019-03-28 12:45:10,701] INFO shutting down (kafka.server.KafkaServer)
[2019-03-28 12:45:10,704] INFO shut down completed (kafka.server.KafkaServer)
[2019-03-28 12:45:10,705] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[2019-03-28 12:45:10,707] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by carrodher** [comment]
Can you provide the _docker-compose.yml_ you are using and the steps to reproduce the issue? Thanks!

**Comment by Aravindumasankar** [comment]
Hello carrodher,
I'm using helm charts [Bitnami Kafka](https://github.com/bitnami/charts/tree/master/bitnami/kafka)
After enabling auth, I get the above error.

**Comment by carrodher** [comment]
Hi, I was going to move this issue to the [Bitnami Charts repository](https://github.com/bitnami/charts/tree/master/bitnami/kafka) but I found you already commented on a closed issue talking about the same topic (https://github.com/bitnami/charts/issues/1018). I just reopened it in order to continue the conversation in that place. I will close this one in order to avoid duplications.
Thanks!
