### ISSUE TITLE
Fatal error during KafkaServer startup. Prepare to shutdown

### ISSUE THREAD

**Issue by 601157475** [bitnami/bitnami-docker-kafka#54]
Fatal error during KafkaServer startup. Prepare to shutdown
this is my docker-compose.yml
version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka_kafka_1
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_INTER_BROKER_USER=interuser
      - KAFKA_INTER_BROKER_PASSWORD=interpassword
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - './kafka.keystore.jks:/opt/bitnami/kafka/conf/certs/kafka.keystore.jks:ro'
      - './kafka.truststore.jks:/opt/bitnami/kafka/conf/certs/kafka.truststore.jks:ro'

**Comment by marcosbc** [comment]
Hi @601157475, unfortunately we could not reproduce your issue.

Please note that you set your hostname to kafka_kafka_1 which is not a valid value. You should set it to a valid value (e.g. mykafka or kafka.example.com).

Then, you need to create your new JKS keystore and truststore with the proper hostname. [See this guide on how to do that](https://github.com/bitnami/bitnami-docker-kafka#security).

Remember to remove all the data and recreate the container each time you want to test a new configuration:

    docker-compose down --volumes
    docker-compose up

If you are still finding issues after that, please share more information such as some logs that may be indicative of your problem.

**Comment by rnl2004** [comment]
Guys good day! I have encountered an issue related to JKS files attached to docker using -v
**Here's my docker command:**
docker run -d -p 9092:9092 -p 9093:9092 -p 9094:9092 --network app-tier --name kafka1 -e KAFKA_CFG_PORT=9092 -e KAFKA_CFG_ZOOKEEPER_CONNECT=myAWSEC2Host:2181 -e KAFKA_CFG_LOG_DIRS="/bitnami/kafka/data"  -e KAFKA_CFG_LISTENERS=SASL_SSL://:9092 -e KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092 -e KAFKA_ZOOKEEPER_PASSWORD=testpass -v /home/ubuntu/docker_scripts/keystore/kafka.keystore.jks:/opt/bitnami/kafka/conf/certs/kafka.keystore.jks -v /home/ubuntu/docker_scripts/truststore/kafka.truststore.jks:/opt/bitnami/kafka/conf/certs/kafka.truststore.jks bitnami/kafka:latest

**Error logs:**
[2019-08-19 09:05:34,439] INFO Successfully logged in. (org.apache.kafka.common.security.authenticator.AbstractLogin)
[2019-08-19 09:05:34,485] ERROR [KafkaServer id=1036] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /opt/bitnami/kafka/conf/certs/kafka.keystore.jks of type JKS
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
        at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:85)
        at kafka.network.Processor.<init>(SocketServer.scala:720)
        at kafka.network.SocketServer.newProcessor(SocketServer.scala:367)
        at kafka.network.SocketServer$$anonfun$kafka$network$SocketServer$$addDataPlaneProcessors$1.apply$mcVI$sp(SocketServer.scala:261)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at kafka.network.SocketServer.kafka$network$SocketServer$$addDataPlaneProcessors(SocketServer.scala:260)
        at kafka.network.SocketServer$$anonfun$createDataPlaneAcceptorsAndProcessors$1.apply(SocketServer.scala:223)
        at kafka.network.SocketServer$$anonfun$createDataPlaneAcceptorsAndProcessors$1.apply(SocketServer.scala:220)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:220)
        at kafka.network.SocketServer.startup(SocketServer.scala:120)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:255)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:84)
        at kafka.Kafka.main(Kafka.scala)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /opt/bitnami/kafka/conf/certs/kafka.keystore.jks of type JKS
        at org.apache.kafka.common.security.ssl.SslEngineBuilder.createSSLContext(SslEngineBuilder.java:160)
        at org.apache.kafka.common.security.ssl.SslEngineBuilder.<init>(SslEngineBuilder.java:102)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:93)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:156)
        ... 17 more
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /opt/bitnami/kafka/conf/certs/kafka.keystore.jks of type JKS
        at org.apache.kafka.common.security.ssl.SslEngineBuilder$SecurityStore.load(SslEngineBuilder.java:289)
        at org.apache.kafka.common.security.ssl.SslEngineBuilder.createSSLContext(SslEngineBuilder.java:142)
        ... 20 more
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:785)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.apache.kafka.common.security.ssl.SslEngineBuilder$SecurityStore.load(SslEngineBuilder.java:286)
        ... 21 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:783)
        ... 26 more
[2019-08-19 09:05:34,488] INFO [KafkaServer id=1036] shutting down (kafka.server.KafkaServer)

**Comment by marcosbc** [comment]
@rnl2004 I have seen that error before, it usually happens when the Keystore wasn't generated or configured properly.

For instance, did you set a passphrase for the keystore? If so you need to set the environment variable `KAFKA_CERTIFICATE_PASSWORD` with the password as described in the [Security](https://github.com/bitnami/bitnami-docker-kafka#security) section in the README.

**Comment by devenpatel2** [comment]
Introduce a 20-second delay between Zookeeper and Kafka. The zookeeper has a session expiry time of 18000ms. It needs this time to declare the old session dead. If the Kafka broker is brought up before this happens, the broker shuts down with "_Error while creating ephemeral at /broker/ids/1, node already exists_". You can thus create an entrypoint 

```bash
#!/bin/bash
sleep 20
/entrypoint.sh /run.sh
```

and then use this entry point when running the docker
```
    entrypoint: /tmp/entrypoint.sh
    volumes: 
        ./entrypoint:/tmp/entrypoint
```
