### ISSUE TITLE
kafka-0 ZkTimeoutException

### ISSUE THREAD

**Issue by pnpavlov** [bitnami/bitnami-docker-kafka#8]
Hello,

I would like to test-out kubeless, looks great! :) 

I run local dev Kubernetes 1.8 on Ubuntu
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
After creating the kafka & K8s PVs, I've started the deployment with the kubeless example YAML
```
$ export RELEASE=v0.3.1
$ kubectl create ns kubeless
$ kubectl create -f https://github.com/kubeless/kubeless/releases/download/$RELEASE/kubeless-rbac-$RELEASE.yaml 
```

I was able to test out an HTTP function, but then I decided to try out the Kafka example and noticed that the Kafka is crashing ( CrashLoopBackOff) and restarting ( Running).

```
$ kubectl -n kubeless get po
NAME                                   READY     STATUS             RESTARTS   AGE
kafka-0                                0/1       CrashLoopBackOff   19         13d
kubeless-controller-659755588f-h5m8p   1/1       Running            1          13d
zoo-0                                  1/1       Running            1          13d

$ kubectl -n kubeless logs kafka-0
Welcome to the Bitnami kafka container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing kafka
kafka   INFO  ==> Validating inputs...
kafka   INFO  ==> Setting '-Xmx5974m -Xms5974m' as heap options...
nami    INFO  kafka successfully initialized
INFO  ==> Starting kafka... 
....
[2017-12-29 14:54:16,623] INFO Initiating client connection, connectString=zookeeper.kubeless:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@79924b (org.apache.zookeeper.ZooKeeper)
[2017-12-29 14:54:27,656] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2017-12-29 14:54:33,657] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2017-12-29 14:54:47,668] INFO Opening socket connection to server zookeeper.kubeless.svc.cluster.local/10.100.57.136:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-12-29 14:54:47,677] INFO Socket connection established to zookeeper.kubeless.svc.cluster.local/10.100.57.136:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-12-29 14:54:47,686] INFO Session establishment complete on server zookeeper.kubeless.svc.cluster.local/10.100.57.136:2181, sessionid = 0x160a2b0d1e40007, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2017-12-29 14:54:47,689] INFO Session: 0x160a2b0d1e40007 closed (org.apache.zookeeper.ZooKeeper)
[2017-12-29 14:54:47,690] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'zookeeper.kubeless:2181' with timeout of 6000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:115)
	at kafka.utils.ZkUtils$.withMetrics(ZkUtils.scala:92)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:346)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:194)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:92)
	at kafka.Kafka.main(Kafka.scala)
[2017-12-29 14:54:47,690] INFO EventThread shut down for session: 0x160a2b0d1e40007 (org.apache.zookeeper.ClientCnxn)
[2017-12-29 14:54:47,692] INFO shutting down (kafka.server.KafkaServer)
[2017-12-29 14:54:47,696] INFO shut down completed (kafka.server.KafkaServer)
[2017-12-29 14:54:47,697] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2017-12-29 14:54:47,699] INFO shutting down (kafka.server.KafkaServer)

$ kubectl -n kubeless logs zoo-0

Welcome to the Bitnami zookeeper container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing zookeeper
nami    INFO  zookeeper successfully initialized
INFO  ==> Starting zookeeper... 
INFO  ==> Starting ZooKeeper...
ZooKeeper JMX enabled by default
Using config: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED
2017-12-29 14:32:44,328 [myid:] - INFO  [main:QuorumPeerConfig@134] - Reading configuration from: /opt/bitnami/zookeeper/bin/../conf/zoo.cfg
2017-12-29 14:33:04,473 [myid:] - WARN  [main:QuorumPeer$QuorumServer@173] - Failed to resolve address: zoo-0.zoo
java.net.UnknownHostException: zoo-0.zoo: Temporary failure in name resolution
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.<init>(QuorumPeer.java:151)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:238)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
2017-12-29 14:33:04,526 [myid:] - ERROR [main:QuorumPeerConfig@345] - Invalid configuration, only one server specified (ignoring)

$ kubectl -it -n kubeless exec zoo-0 cat /etc/hosts
...
192.168.195.239	zoo-0.zoo.kubeless.svc.cluster.local	zoo-0
```
Changing the zoo StatefulSet from zoo-0.zoo to seems to fix the zookeeper resolving host name issue .. with 
```
      containers:
      - env:
        - name: ZOO_SERVERS
          value: server.1=zoo-0:2888:3888:participant
```
I see 
`2017-12-29 15:18:29,234 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: zoo-0.zoo to address: zoo-0.zoo/192.168.195.243`

but still the kafka fails to start of course... Any hints why the default demo setup does not work for me? My kube-system seems to be Running and I could not find any errors in the Calico logs...

Regards,
Pavel

**Comment by pnpavlov** [comment]
Hello,
Problem seems to be related to my local cluster setup and proxy settings... closing this issue. Container starts when I use minikube for example... Will keep looking for my cluster proxy problem... 
Regards, Pavel
